
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPlayerGui.java
 *
 * Created on 24.10.2016, 11:48:27
 */
package gui;

        import gameLogic.Game;

/**
 *
 * @author admin
 */
public class AddPlayer extends javax.swing.JFrame {

    /** Creates new form AddPlayerGui */
//    public AddPlayer(gameLogic.Game game) {
//        initComponents();
//        bCreateNewPlayer.addActionListener(game);
//    }
    public AddPlayer(Game game) {
        initComponents();
        bCreateNewPlayer.addActionListener(game.new CreatePlayerActivity());
    }

    public AddPlayer() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        textAge = new javax.swing.JTextField();
        bCreateNewPlayer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Имя");

        jLabel2.setText("Возвраст");

        textName.addActionListener(this::textNameActionPerformed);

        textAge.addActionListener(this::textAgeActionPerformed);

        bCreateNewPlayer.setText("Создать");
        bCreateNewPlayer.addActionListener(this::bCreateNewPlayerPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textName)
                                        .addComponent(textAge, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(bCreateNewPlayer)
                                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(bCreateNewPlayer)))
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getAge() throws NumberFormatException {
        return Integer.valueOf(textAge.getText());
    }

    public void error() {
        textAge.setText("введите возраст");
    }

    public void clear() {
        textName.setText("введите имя");
        textAge.setText("введите возраст");
    }

    public String getNewName() {
        return textName.getText();
    }

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void bCreateNewPlayerPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCreateNewPlayerPerformed
//        gameLogic.Player p = new gameLogic.Player(textName.getText(), (int) Integer.valueOf(textAge.getText()), 0, 0, 0, 0);
    }//GEN-LAST:event_bCreateNewPlayerPerformed

    private void textAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new AddPlayer().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCreateNewPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textAge;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables
}
