/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowWinner.java
 *
 * Created on 25.10.2016, 19:53:38
 */
package gui;

import gameLogic.Game;

import java.awt.*;

/**
 * @author admin
 */
public class ShowWinner extends javax.swing.JFrame {

    /**
     * Creates new form ShowWinner
     */
    private ShowWinner() {
        initComponents();
    }

    public ShowWinner(Game game) {
        initComponents();
        bStartNewGame.addActionListener(game.new CreateNewGameActivity());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton jButton1 = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        lableWinnerGame = new javax.swing.JLabel();
        bStartNewGame = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", Font.PLAIN, 14));
        jLabel1.setText("Поздравляем победителя:");

        lableWinnerGame.setFont(new java.awt.Font("Calibri", Font.PLAIN, 14)); // NOI18N
        lableWinnerGame.setText("jLabel2");

        bStartNewGame.setFont(new java.awt.Font("Calibri", Font.PLAIN, 14));
        bStartNewGame.setText("Новая игра");
        bStartNewGame.addActionListener(evt -> bStartNewGameActionPerformed());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(jLabel1)
                                .addContainerGap(106, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(174, Short.MAX_VALUE)
                                .addComponent(lableWinnerGame)
                                .addGap(172, 172, 172))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(bStartNewGame)
                                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lableWinnerGame)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bStartNewGame)
                                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setWinnerName(String s) {
        lableWinnerGame.setText(s);

    }

    private void bStartNewGameActionPerformed() {//GEN-FIRST:event_bStartNewGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bStartNewGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new ShowWinner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bStartNewGame;
    private javax.swing.JLabel lableWinnerGame;
    // End of variables declaration//GEN-END:variables
}
